### ISSUE TITLE
Not able to build and deploy sample application - extorderapp on BTP Cloud Foundry

### ISSUE THREAD

**Issue by I340866** [SAP/cloud-sdk#309]
## Issue Description
I'm unable to deploy sample application - cloud-s4-sample-ext-extorderapp on Business Technology Platform(Cloud Foundry) since this application is outdated as it supports SCP Neo environment.
Can you please help us in upgrading the maven dependencies and make a successful build for this sample application so that we are able to deploy it on BTP Cloud Foundry and resume with our testing. 

### Impact / Priority
We are stuck with testing of Side by Side Extensibility test scenario of S/4 HANA Cloud System as part of 3SL 2105 CBC. 

Timeline: As soon as possible

## Error Message
I tried deploying existing application build on BTP Cloud Foundry and got below errors 
```
2021-06-01T13:10:29.399+0000 [API/1] OUT Updated app with guid 453b1462-cc30-45a0-bb42-bf944f400e8b ({"state"=>"STARTED"})
2021-06-01T13:10:29.524+0000 [CELL/0] OUT Cell 569718e1-af1c-4383-8517-49470cc1df88 creating container for instance d4bcb809-f313-4052-563a-9220
2021-06-01T13:10:31.241+0000 [CELL/0] OUT Cell 569718e1-af1c-4383-8517-49470cc1df88 successfully created container for instance d4bcb809-f313-4052-563a-9220
2021-06-01T13:10:31.454+0000 [CELL/0] OUT Downloading droplet...
2021-06-01T13:10:34.991+0000 [CELL/0] OUT Downloaded droplet (75.5M)
2021-06-01T13:10:35.758+0000 [APP/PROC/WEB/0] OUT JVM Memory Configuration: -Xmx430528K -Xss1M -XX:ReservedCodeCacheSize=240M -XX:MaxDirectMemorySize=10M -XX:MaxMetaspaceSize=106047K
2021-06-01T13:10:36.251+0000 [APP/PROC/WEB/0] OUT [CONTAINER] org.apache.coyote.http11.Http11NioProtocol         INFO    Initializing ProtocolHandler ["http-nio-8080"]
2021-06-01T13:10:36.303+0000 [APP/PROC/WEB/0] OUT [CONTAINER] org.apache.catalina.startup.Catalina               INFO    Server initialization in [811] milliseconds
2021-06-01T13:10:36.312+0000 [APP/PROC/WEB/0] OUT [CONTAINER] org.apache.catalina.core.StandardService           INFO    Starting service [Catalina]
2021-06-01T13:10:36.312+0000 [APP/PROC/WEB/0] OUT [CONTAINER] org.apache.catalina.core.StandardEngine            INFO    Starting Servlet engine: [Apache Tomcat/9.0.44]
2021-06-01T13:10:36.333+0000 [APP/PROC/WEB/0] OUT [CONTAINER] org.apache.catalina.startup.HostConfig             INFO    Deploying web application directory [/home/vcap/app/.java-buildpack/tomcat/webapps/ROOT]
2021-06-01T13:10:40.619+0000 [APP/PROC/WEB/0] OUT [CONTAINER] org.apache.catalina.startup.HostConfig             SEVERE  Error deploying web application directory [/home/vcap/app/.java-buildpack/tomcat/webapps/ROOT]
2021-06-01T13:10:40.619+0000 [APP/PROC/WEB/0] OUT java.lang.IllegalStateException: Error starting child
2021-06-01T13:10:40.619+0000 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:720)
2021-06-01T13:10:40.619+0000 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:690)
2021-06-01T13:10:40.619+0000 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:706)
2021-06-01T13:10:40.619+0000 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1184)
2021-06-01T13:10:40.619+0000 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1925)
2021-06-01T13:10:40.619+0000 [APP/PROC/WEB/0] OUT 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2021-06-01T13:10:40.619+0000 [APP/PROC/WEB/0] OUT 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2021-06-01T13:10:40.619+0000 [APP/PROC/WEB/0] OUT 	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
2021-06-01T13:10:40.619+0000 [APP/PROC/WEB/0] OUT 	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
2021-06-01T13:10:40.619+0000 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.startup.HostConfig.deployDirectories(HostConfig.java:1094)
2021-06-01T13:10:40.619+0000 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:476)
2021-06-01T13:10:40.619+0000 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1611)
2021-06-01T13:10:40.619+0000 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:319)
2021-06-01T13:10:40.619+0000 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
2021-06-01T13:10:40.619+0000 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
2021-06-01T13:10:40.619+0000 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
2021-06-01T13:10:40.619+0000 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:936)
2021-06-01T13:10:40.619+0000 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:843)
2021-06-01T13:10:40.619+0000 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
2021-06-01T13:10:40.619+0000 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384)
2021-06-01T13:10:40.619+0000 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374)
2021-06-01T13:10:40.619+0000 [APP/PROC/WEB/0] OUT 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2021-06-01T13:10:40.619+0000 [APP/PROC/WEB/0] OUT 	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
2021-06-01T13:10:40.619+0000 [APP/PROC/WEB/0] OUT 	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
2021-06-01T13:10:40.619+0000 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909)
2021-06-01T13:10:40.619+0000 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
2021-06-01T13:10:40.619+0000 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
2021-06-01T13:10:40.619+0000 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:434)
2021-06-01T13:10:40.619+0000 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
2021-06-01T13:10:40.619+0000 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930)
2021-06-01T13:10:40.619+0000 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
2021-06-01T13:10:40.619+0000 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.startup.Catalina.start(Catalina.java:772)
2021-06-01T13:10:40.619+0000 [APP/PROC/WEB/0] OUT 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-06-01T13:10:40.619+0000 [APP/PROC/WEB/0] OUT 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-06-01T13:10:40.619+0000 [APP/PROC/WEB/0] OUT 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-06-01T13:10:40.619+0000 [APP/PROC/WEB/0] OUT 	at java.lang.reflect.Method.invoke(Method.java:498)
2021-06-01T13:10:40.619+0000 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:342)
2021-06-01T13:10:40.619+0000 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:473)
2021-06-01T13:10:40.619+0000 [APP/PROC/WEB/0] OUT Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[]]
2021-06-01T13:10:40.619+0000 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.util.LifecycleBase.handleSubClassException(LifecycleBase.java:440)
2021-06-01T13:10:40.619+0000 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:198)
2021-06-01T13:10:40.619+0000 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:717)
2021-06-01T13:10:40.619+0000 [APP/PROC/WEB/0] OUT 	... 37 more
2021-06-01T13:10:40.619+0000 [APP/PROC/WEB/0] OUT Caused by: java.lang.NoClassDefFoundError: Lorg/slf4j/Logger;
2021-06-01T13:10:40.619+0000 [APP/PROC/WEB/0] OUT 	at java.lang.Class.getDeclaredFields0(Native Method)
2021-06-01T13:10:40.619+0000 [APP/PROC/WEB/0] OUT 	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
2021-06-01T13:10:40.619+0000 [APP/PROC/WEB/0] OUT 	at java.lang.Class.getDeclaredFields(Class.java:1916)
2021-06-01T13:10:40.619+0000 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.util.Introspection.getDeclaredFields(Introspection.java:104)
2021-06-01T13:10:40.619+0000 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.startup.WebAnnotationSet.loadFieldsAnnotation(WebAnnotationSet.java:269)
2021-06-01T13:10:40.619+0000 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.startup.WebAnnotationSet.loadApplicationListenerAnnotations(WebAnnotationSet.java:89)
2021-06-01T13:10:40.619+0000 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.startup.WebAnnotationSet.loadApplicationAnnotations(WebAnnotationSet.java:67)
2021-06-01T13:10:40.619+0000 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.startup.ContextConfig.applicationAnnotationsConfig(ContextConfig.java:332)
2021-06-01T13:10:40.619+0000 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:989)
2021-06-01T13:10:40.619+0000 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:303)
2021-06-01T13:10:40.619+0000 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
2021-06-01T13:10:40.619+0000 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5082)
2021-06-01T13:10:40.619+0000 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
2021-06-01T13:10:40.619+0000 [APP/PROC/WEB/0] OUT 	... 38 more
2021-06-01T13:10:40.619+0000 [APP/PROC/WEB/0] OUT Caused by: java.lang.ClassNotFoundException: org.slf4j.Logger
2021-06-01T13:10:40.619+0000 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1364)
2021-06-01T13:10:40.619+0000 [APP/PROC/WEB/0] OUT 	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1187)
2021-06-01T13:10:40.619+0000 [APP/PROC/WEB/0] OUT 	... 51 more
2021-06-01T13:10:40.620+0000 [APP/PROC/WEB/0] OUT [CONTAINER] org.apache.catalina.startup.HostConfig             INFO    Deployment of web application directory [/home/vcap/app/.java-buildpack/tomcat/webapps/ROOT] has finished in [4,286] ms
2021-06-01T13:10:40.621+0000 [APP/PROC/WEB/0] OUT [CONTAINER] pplicationStartupFailureDetectingLifecycleListener SEVERE  Error: Application '' failed (state = FAILED): see Tomcat's logs for details. Halting Tomcat.
2021-06-01T13:10:40.724+0000 [APP/PROC/WEB/0] OUT Exit status 148
2021-06-01T13:10:45.965+0000 [CELL/0] OUT Cell 569718e1-af1c-4383-8517-49470cc1df88 stopping instance d4bcb809-f313-4052-563a-9220
2021-06-01T13:10:45.965+0000 [CELL/0] OUT Cell 569718e1-af1c-4383-8517-49470cc1df88 destroying container for instance d4bcb809-f313-4052-563a-9220
2021-06-01T13:10:45.989+0000 [API/0] OUT Process has crashed with type: "web"
2021-06-01T13:10:46.045+0000 [API/0] OUT App instance exited with guid 453b1462-cc30-45a0-bb42-bf944f400e8b payload: {"instance"=>"d4bcb809-f313-4052-563a-9220", "index"=>0, "cell_id"=>"569718e1-af1c-4383-8517-49470cc1df88", "reason"=>"CRASHED", "exit_description"=>"APP/PROC/WEB: Exited with status 148", "crash_count"=>1, "crash_timestamp"=>1622553045929083820, "version"=>"07ef07bc-fc1f-4aa1-a1b8-da508ddafcbf"}
2021-06-01T13:10:46.127+0000 [CELL/0] OUT Cell 5dc4bed0-1010-41f1-8466-2fdc9428e257 creating container for instance 8e3968a8-0609-4c92-6c3f-f085
2021-06-01T13:10:47.885+0000 [CELL/0] OUT Cell 5dc4bed0-1010-41f1-8466-2fdc9428e257 successfully created container for instance 8e3968a8-0609-4c92-6c3f-f085
2021-06-01T13:10:48.291+0000 [CELL/0] OUT Downloading droplet...
2021-06-01T13:10:48.301+0000 [PROXY/0] OUT Exit status 137
2021-06-01T13:10:48.339+0000 [CELL/0] OUT Cell 569718e1-af1c-4383-8517-49470cc1df88 successfully destroyed container for instance d4bcb809-f313-4052-563a-9220
2021-06-01T13:10:51.987+0000 [CELL/0] OUT Downloaded droplet (75.5M)
2021-06-01T13:10:52.599+0000 [APP/PROC/WEB/0] OUT JVM Memory Configuration: -Xmx430528K -Xss1M -XX:ReservedCodeCacheSize=240M -XX:MaxDirectMemorySize=10M -XX:MaxMetaspaceSize=106047K
```

## Project Details
Implementation Steps (Ordering Scenario)
https://help.sap.com/viewer/4316f97a90ff48948fb7f212ecabf964/SHIP/en-US/c39831353b1e4ae2bad2fa20ac3a152f.html 

- Project type, for example:
  - [ ] CAP Project
  - [x] SAP Cloud SDK Maven Archetype
  - [ ] None of the above:
- Platform:
  - [ x] Cloud Foundry
  - [ x] Neo

---
-pom files
[pom_files.zip](https://github.com/SAP/cloud-sdk/files/6584839/pom_files.zip)

**Comment by artemkovalyov** [comment]
Hi @I340866 

This is rather an old App that was created using the SDK but not by the SDK team. We're trying to reach out to the team that created it to see if they can port the App to the latest SDK version. We would hardly have time and resources at the moment to do that.

The task doesn't boil down just to dependency updates and will require full migration to a new SDK version. We'll keep you posted when we get feedback from the colleagues.

**Comment by I340866** [comment]
Created the issue in this internal GH repo.

**Comment by I340866** [comment]
Moved this issue to Enterprise GH repo.

**Comment by I340866** [comment]
Enterprise GH repo link - https://github.wdf.sap.corp/MA/sdk/issues/5555#issue-4152927
