### ISSUE TITLE
generate-odata-client results in Unexpected token 'export'

### ISSUE THREAD

**Issue by levinanton** [SAP/cloud-sdk#433]
**Describe the bug**

Execution of

```
generate-odata-client --inputDir /in --outputDir /out
```

fails with `ERROR uncaughtException: Unexpected token 'export'`

**To Reproduce**

1. Install `npm install -g @sap-cloud-sdk/generator`
2. Execute `generate-odata-client --inputDir /in --outputDir /out`
3. See error in terminal

**Expected behavior**

Get generated output.

**Used Versions:**
 - node version v13.6.0
 - npm version 6.13.4
 - "@sap-cloud-sdk/generator": "1.27.0"

**Log file**

```
[2020-08-27T12:13:16.337Z] ERROR  uncaughtException: Unexpected token 'export'

/usr/local/lib/node_modules/@sap-cloud-sdk/generator/node_modules/uuid/dist/esm-browser/index.js:1

export { default as v1 } from './v1.js';

^^^^^^


SyntaxError: Unexpected token 'export'

  at wrapSafe (internal/modules/cjs/loader.js:1060:16)

  at Module._compile (internal/modules/cjs/loader.js:1108:27)

  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)

  at Module.load (internal/modules/cjs/loader.js:993:32)

  at Function.Module._load (internal/modules/cjs/loader.js:892:14)

  at Module.require (internal/modules/cjs/loader.js:1033:19)

  at require (internal/modules/cjs/helpers.js:72:18)

  at Object.<anonymous> (/usr/local/lib/node_modules/@sap-cloud-sdk/generator/node_modules/@sap-cloud-sdk/core/dist/odata/v2/odata-batch-change-set.js:5:14)

  at Module._compile (internal/modules/cjs/loader.js:1144:30)

  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
```

**Comment by marikaner** [comment]
Hey @levinanton,

this is due to the fact that you are using an outdated unstable version of node. Please take a look at the [release schedule of node](https://github.com/uuidjs/uuid/issues/466). It states that odd-numbered versions become unsupported after 6 months.  In addition to that 13.6 is quite an old version - with 13.14 the generation works again. I would recommend to either downgrade to node 12 or upgrade to node 14.

I hope that helps!

**Comment by levinanton** [comment]
Changing to node v13.14.0 solved the problem. Many thanks for your hint.
